// Package repos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package repos

import (
	context "context"

	entities "github.com/ikaiguang/go-snowflake-node-id/node-id/entity"
)

// SnowflakeWorkerNodeRepo repo
type SnowflakeWorkerNodeRepo interface {
	Create(ctx context.Context, dataModel *entities.SnowflakeWorkerNode) error
	Update(ctx context.Context, dataModel *entities.SnowflakeWorkerNode) error
	QueryOneByNodeUUID(ctx context.Context, nodeUUID string) (dataModel *entities.SnowflakeWorkerNode, isNotFound bool, err error)
	QueryMaxNodeIDByInstanceID(ctx context.Context, instanceID string) (dataModels []*entities.InstanceMaxNodeID, err error)
	QueryIdleNodeIDByInstanceID(ctx context.Context, req *entities.InstanceIdleNodeIDReq) (dataModel *entities.InstanceMaxNodeID, isNotFound bool, err error)
}
