// Package repos
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package repos

import (
	context "context"

	entities "github.com/ikaiguang/go-snowflake-node-id/node-id/entity"
)

// SnowflakeWorkerNodeRepo repo
type SnowflakeWorkerNodeRepo interface {
	StoreNodeID(ctx context.Context, dataModel *entities.SnowflakeWorkerNode) (err error)
	QueryMaxNodeIDByInstanceID(ctx context.Context, instanceID string) (dataModels []*entities.InstanceMaxNodeID, err error)
}
