// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/snowflake-service/v1/services/snowflake.service.v1.proto

package snowflakeservicev1

import (
	context "context"
	resources "github.com/ikaiguang/go-snowflake-node-id/api/snowflake-service/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SrvSnowflakeWorkerClient is the client API for SrvSnowflakeWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvSnowflakeWorkerClient interface {
	GetNodeId(ctx context.Context, in *resources.GetNodeIdReq, opts ...grpc.CallOption) (*resources.SnowflakeWorker, error)
	ExtendNodeId(ctx context.Context, in *resources.ExtendNodeIdReq, opts ...grpc.CallOption) (*resources.Result, error)
}

type srvSnowflakeWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvSnowflakeWorkerClient(cc grpc.ClientConnInterface) SrvSnowflakeWorkerClient {
	return &srvSnowflakeWorkerClient{cc}
}

func (c *srvSnowflakeWorkerClient) GetNodeId(ctx context.Context, in *resources.GetNodeIdReq, opts ...grpc.CallOption) (*resources.SnowflakeWorker, error) {
	out := new(resources.SnowflakeWorker)
	err := c.cc.Invoke(ctx, "/snowflake.service.api.snowflakeservicev1.SrvSnowflakeWorker/GetNodeId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvSnowflakeWorkerClient) ExtendNodeId(ctx context.Context, in *resources.ExtendNodeIdReq, opts ...grpc.CallOption) (*resources.Result, error) {
	out := new(resources.Result)
	err := c.cc.Invoke(ctx, "/snowflake.service.api.snowflakeservicev1.SrvSnowflakeWorker/ExtendNodeId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvSnowflakeWorkerServer is the server API for SrvSnowflakeWorker service.
// All implementations must embed UnimplementedSrvSnowflakeWorkerServer
// for forward compatibility
type SrvSnowflakeWorkerServer interface {
	GetNodeId(context.Context, *resources.GetNodeIdReq) (*resources.SnowflakeWorker, error)
	ExtendNodeId(context.Context, *resources.ExtendNodeIdReq) (*resources.Result, error)
	mustEmbedUnimplementedSrvSnowflakeWorkerServer()
}

// UnimplementedSrvSnowflakeWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedSrvSnowflakeWorkerServer struct {
}

func (UnimplementedSrvSnowflakeWorkerServer) GetNodeId(context.Context, *resources.GetNodeIdReq) (*resources.SnowflakeWorker, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeId not implemented")
}
func (UnimplementedSrvSnowflakeWorkerServer) ExtendNodeId(context.Context, *resources.ExtendNodeIdReq) (*resources.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendNodeId not implemented")
}
func (UnimplementedSrvSnowflakeWorkerServer) mustEmbedUnimplementedSrvSnowflakeWorkerServer() {}

// UnsafeSrvSnowflakeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvSnowflakeWorkerServer will
// result in compilation errors.
type UnsafeSrvSnowflakeWorkerServer interface {
	mustEmbedUnimplementedSrvSnowflakeWorkerServer()
}

func RegisterSrvSnowflakeWorkerServer(s grpc.ServiceRegistrar, srv SrvSnowflakeWorkerServer) {
	s.RegisterService(&SrvSnowflakeWorker_ServiceDesc, srv)
}

func _SrvSnowflakeWorker_GetNodeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.GetNodeIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvSnowflakeWorkerServer).GetNodeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snowflake.service.api.snowflakeservicev1.SrvSnowflakeWorker/GetNodeId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvSnowflakeWorkerServer).GetNodeId(ctx, req.(*resources.GetNodeIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvSnowflakeWorker_ExtendNodeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.ExtendNodeIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvSnowflakeWorkerServer).ExtendNodeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snowflake.service.api.snowflakeservicev1.SrvSnowflakeWorker/ExtendNodeId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvSnowflakeWorkerServer).ExtendNodeId(ctx, req.(*resources.ExtendNodeIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvSnowflakeWorker_ServiceDesc is the grpc.ServiceDesc for SrvSnowflakeWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvSnowflakeWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snowflake.service.api.snowflakeservicev1.SrvSnowflakeWorker",
	HandlerType: (*SrvSnowflakeWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeId",
			Handler:    _SrvSnowflakeWorker_GetNodeId_Handler,
		},
		{
			MethodName: "ExtendNodeId",
			Handler:    _SrvSnowflakeWorker_ExtendNodeId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/snowflake-service/v1/services/snowflake.service.v1.proto",
}
