// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: api/node-id/v1/services/node-id.service.v1.proto

package servicev1

import (
	context "context"
	api "github.com/ikaiguang/go-snowflake-node-id/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SrvWorkerClient is the client API for SrvWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrvWorkerClient interface {
	GetNodeId(ctx context.Context, in *api.GetNodeIdReq, opts ...grpc.CallOption) (*api.SnowflakeWorkerNode, error)
	ExtendNodeId(ctx context.Context, in *api.ExtendNodeIdReq, opts ...grpc.CallOption) (*api.Result, error)
}

type srvWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewSrvWorkerClient(cc grpc.ClientConnInterface) SrvWorkerClient {
	return &srvWorkerClient{cc}
}

func (c *srvWorkerClient) GetNodeId(ctx context.Context, in *api.GetNodeIdReq, opts ...grpc.CallOption) (*api.SnowflakeWorkerNode, error) {
	out := new(api.SnowflakeWorkerNode)
	err := c.cc.Invoke(ctx, "/node.id.api.servicev1.SrvWorker/GetNodeId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvWorkerClient) ExtendNodeId(ctx context.Context, in *api.ExtendNodeIdReq, opts ...grpc.CallOption) (*api.Result, error) {
	out := new(api.Result)
	err := c.cc.Invoke(ctx, "/node.id.api.servicev1.SrvWorker/ExtendNodeId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvWorkerServer is the server API for SrvWorker service.
// All implementations must embed UnimplementedSrvWorkerServer
// for forward compatibility
type SrvWorkerServer interface {
	GetNodeId(context.Context, *api.GetNodeIdReq) (*api.SnowflakeWorkerNode, error)
	ExtendNodeId(context.Context, *api.ExtendNodeIdReq) (*api.Result, error)
	mustEmbedUnimplementedSrvWorkerServer()
}

// UnimplementedSrvWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedSrvWorkerServer struct {
}

func (UnimplementedSrvWorkerServer) GetNodeId(context.Context, *api.GetNodeIdReq) (*api.SnowflakeWorkerNode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeId not implemented")
}
func (UnimplementedSrvWorkerServer) ExtendNodeId(context.Context, *api.ExtendNodeIdReq) (*api.Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendNodeId not implemented")
}
func (UnimplementedSrvWorkerServer) mustEmbedUnimplementedSrvWorkerServer() {}

// UnsafeSrvWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvWorkerServer will
// result in compilation errors.
type UnsafeSrvWorkerServer interface {
	mustEmbedUnimplementedSrvWorkerServer()
}

func RegisterSrvWorkerServer(s grpc.ServiceRegistrar, srv SrvWorkerServer) {
	s.RegisterService(&SrvWorker_ServiceDesc, srv)
}

func _SrvWorker_GetNodeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.GetNodeIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvWorkerServer).GetNodeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.id.api.servicev1.SrvWorker/GetNodeId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvWorkerServer).GetNodeId(ctx, req.(*api.GetNodeIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SrvWorker_ExtendNodeId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(api.ExtendNodeIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvWorkerServer).ExtendNodeId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.id.api.servicev1.SrvWorker/ExtendNodeId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvWorkerServer).ExtendNodeId(ctx, req.(*api.ExtendNodeIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvWorker_ServiceDesc is the grpc.ServiceDesc for SrvWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.id.api.servicev1.SrvWorker",
	HandlerType: (*SrvWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeId",
			Handler:    _SrvWorker_GetNodeId_Handler,
		},
		{
			MethodName: "ExtendNodeId",
			Handler:    _SrvWorker_ExtendNodeId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/node-id/v1/services/node-id.service.v1.proto",
}
