// Package schemas
// Code generated by ikaiguang. <https://github.com/ikaiguang>
package schema

import (
	migrationuitl "github.com/ikaiguang/go-srv-kit/data/migration"
	gorm "gorm.io/gorm"
	"time"
)

var _ = time.Time{}

// SnowflakeWorkerSchema SnowflakeWorker
var SnowflakeWorkerSchema SnowflakeWorker

// NewSnowflakeWorker new schema
func NewSnowflakeWorker() *SnowflakeWorker {
	return &SnowflakeWorker{}
}

// SnowflakeWorker ENGINE InnoDB CHARSET utf8mb4 COMMENT '雪花算法节点ID'
type SnowflakeWorker struct {
	Id                   uint64    `gorm:"column:id;primaryKey;type:uint;autoIncrement;comment:id" json:"id"`
	NodeUuid             string    `gorm:"column:node_uuid;unique;type:string;size:255;not null;default:'';comment:唯一ID；instance_id+node_id" json:"node_uuid"`
	InstanceLaunchTime   time.Time `gorm:"column:instance_launch_time;type:time;not null;comment:实例启动时间" json:"instance_launch_time"`
	InstanceExtendTime   time.Time `gorm:"column:instance_extend_time;index;type:time;not null;comment:实例续期时间" json:"instance_extend_time"`
	InstanceId           string    `gorm:"column:instance_id;index;type:string;size:255;not null;default:'';comment:实例ID" json:"instance_id"`
	SnowflakeNodeId      int32     `gorm:"column:snowflake_node_id;type:int;not null;default:0;comment:雪花算法节点id" json:"snowflake_node_id"`
	InstanceName         string    `gorm:"column:instance_name;type:string;size:255;not null;default:'';comment:实例名称" json:"instance_name"`
	InstanceEndpointList string    `gorm:"column:instance_endpoint_list;type:json;not null;comment:实例端点数组" json:"instance_endpoint_list"`
	InstanceMetadata     *string   `gorm:"column:instance_metadata;type:json;comment:实例元数据" json:"instance_metadata"`
	CreatedTime          time.Time `gorm:"column:created_time;type:time;not null;comment:创建时间" json:"created_time"`
}

// TableName table name
func (s *SnowflakeWorker) TableName() string {
	return "snowflake_worker_node"
}

// CreateTableMigrator create table migrator
func (s *SnowflakeWorker) CreateTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewCreateTable(migrator, s)
}

// DropTableMigrator create table migrator
func (s *SnowflakeWorker) DropTableMigrator(migrator gorm.Migrator) migrationuitl.MigrationRepo {
	return migrationuitl.NewDropTable(migrator, s)
}
