// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: api/common/v1/env.v1.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvEnum_Env int32

const (
	// UNKNOWN 未知
	EnvEnum_UNKNOWN EnvEnum_Env = 0
	// DEVELOP 开发环境
	EnvEnum_DEVELOP EnvEnum_Env = 1
	// TESTING 测试环境
	EnvEnum_TESTING EnvEnum_Env = 2
	// PREVIEW 预发布 环境
	EnvEnum_PREVIEW EnvEnum_Env = 3
	// PRODUCTION 生产环境
	EnvEnum_PRODUCTION EnvEnum_Env = 4
)

// Enum value maps for EnvEnum_Env.
var (
	EnvEnum_Env_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEVELOP",
		2: "TESTING",
		3: "PREVIEW",
		4: "PRODUCTION",
	}
	EnvEnum_Env_value = map[string]int32{
		"UNKNOWN":    0,
		"DEVELOP":    1,
		"TESTING":    2,
		"PREVIEW":    3,
		"PRODUCTION": 4,
	}
)

func (x EnvEnum_Env) Enum() *EnvEnum_Env {
	p := new(EnvEnum_Env)
	*p = x
	return p
}

func (x EnvEnum_Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvEnum_Env) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_env_v1_proto_enumTypes[0].Descriptor()
}

func (EnvEnum_Env) Type() protoreflect.EnumType {
	return &file_api_common_v1_env_v1_proto_enumTypes[0]
}

func (x EnvEnum_Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvEnum_Env.Descriptor instead.
func (EnvEnum_Env) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_env_v1_proto_rawDescGZIP(), []int{0, 0}
}

// Env app 环境
type EnvEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnvEnum) Reset() {
	*x = EnvEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_common_v1_env_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvEnum) ProtoMessage() {}

func (x *EnvEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_env_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvEnum.ProtoReflect.Descriptor instead.
func (*EnvEnum) Descriptor() ([]byte, []int) {
	return file_api_common_v1_env_v1_proto_rawDescGZIP(), []int{0}
}

var File_api_common_v1_env_v1_proto protoreflect.FileDescriptor

var file_api_common_v1_env_v1_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x6e, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x73, 0x6e,
	0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0x22, 0x54, 0x0a, 0x07,
	0x45, 0x6e, 0x76, 0x45, 0x6e, 0x75, 0x6d, 0x22, 0x49, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x45, 0x53, 0x54,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x56, 0x49, 0x45, 0x57,
	0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x04, 0x42, 0x81, 0x01, 0x0a, 0x1e, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x76, 0x31, 0x42, 0x1b, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x56, 0x31, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x6b, 0x61, 0x69, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x6e,
	0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x69, 0x64, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_common_v1_env_v1_proto_rawDescOnce sync.Once
	file_api_common_v1_env_v1_proto_rawDescData = file_api_common_v1_env_v1_proto_rawDesc
)

func file_api_common_v1_env_v1_proto_rawDescGZIP() []byte {
	file_api_common_v1_env_v1_proto_rawDescOnce.Do(func() {
		file_api_common_v1_env_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_v1_env_v1_proto_rawDescData)
	})
	return file_api_common_v1_env_v1_proto_rawDescData
}

var file_api_common_v1_env_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_common_v1_env_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_v1_env_v1_proto_goTypes = []interface{}{
	(EnvEnum_Env)(0), // 0: snowflake.service.api.commonv1.EnvEnum.Env
	(*EnvEnum)(nil),  // 1: snowflake.service.api.commonv1.EnvEnum
}
var file_api_common_v1_env_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_common_v1_env_v1_proto_init() }
func file_api_common_v1_env_v1_proto_init() {
	if File_api_common_v1_env_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_common_v1_env_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_v1_env_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_env_v1_proto_goTypes,
		DependencyIndexes: file_api_common_v1_env_v1_proto_depIdxs,
		EnumInfos:         file_api_common_v1_env_v1_proto_enumTypes,
		MessageInfos:      file_api_common_v1_env_v1_proto_msgTypes,
	}.Build()
	File_api_common_v1_env_v1_proto = out.File
	file_api_common_v1_env_v1_proto_rawDesc = nil
	file_api_common_v1_env_v1_proto_goTypes = nil
	file_api_common_v1_env_v1_proto_depIdxs = nil
}
